### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LovesAsuna** [hazae41/mc-fakeprotocol#1]
How can i can a protocol number?
![I$}5C`(}LPHKKQ@P5TDN2VK](https://user-images.githubusercontent.com/32810896/62537497-1be91f00-b883-11e9-8d16-274f0f3c78ef.png)

**Comment by friedwaffelrixe** [comment]
If you mean how can I add a protocol number, simply add it to the list with a comma separating it(Example [107, 108, 109, 110, 210, 315, 316, 335, 338, 340 ,͟ ͟4͟9͟8͟]
There's a helpful list of protocol numbers here: https://wiki.vg/Protocol_version_numbers

**Comment by LovesAsuna** [comment]
Yes,that's what i mean.Thanks a lot
